# Author : Arda OZTURK
# Date   : 01/05/2016

# Assignment 1 
# Plot 4

# download an unzip 'household_power_consumption.txt' file
# Under your root dir in a folder called 'data' 

dataFile <- "./data/household_power_consumption.txt"

# Read file
# First row includes haeders so set HEADER=TRUE

data <- read.table(dataFile, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")

# Sub set requested data only

plotData <- subset(data, (Date == "1/2/2007" | Date == "2/2/2007"))

# alterlative way to subset
# plotData <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]

# You cab check the date before moving on 
# str(plotData)

# Create plot variables as numeric data sets


globalActivePower <- as.numeric(plotData$Global_active_power)
globalReactivePower <- as.numeric(plotData$Global_reactive_power)
voltage <- as.numeric(plotData$Voltage)
subMetering1 <- as.numeric(plotData$Sub_metering_1)
subMetering2 <- as.numeric(plotData$Sub_metering_2)
subMetering3 <- as.numeric(plotData$Sub_metering_3)

# Create another data set which will be generated by 
# combining date and time values

plotDataDayTime <- strptime(paste(plotData$Date, plotData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 

# Configure plot grid setup, make it (2x2)

par(mfcol = c(2, 2)) 

# Add plots one by one
#=====================================================================
# 1.st Plot (top left)

plot(datetime, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)

#=====================================================================
# 2.nd Plot (bottom left)
# Generate an empty plot on screen device 

plot(datetime, subMetering1, type="n", ylab="Energy Submetering", xlab="")

# Add new data once at a time with requested color feature
# Default color is black

lines(datetime, subMetering1, type="l")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")

legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))

#=====================================================================
# 3.rd plot (top right)

plot(datetime, voltage, type="l", xlab="datetime", ylab="Voltage")

#=====================================================================
# 4.th plot (bottom right)

plot(datetime, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")

# Create a png file with given specs (480x480)

dev.copy(png, file = "plot4.png", width=480, height=480)

# Close the file device to finish with the file

dev.off()
