# Author : Arda OZTURK
# Date   : 01/05/2016

# Assignment 1 
# Plot 3

# download an unzip 'household_power_consumption.txt' file
# Under your root dir in a folder called 'data' 

dataFile <- "./data/household_power_consumption.txt"

# Read file
# First row includes haeders so set HEADER=TRUE

data <- read.table(dataFile, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")

# Sub set requested data only

plotData <- subset(data, (Date == "1/2/2007" | Date == "2/2/2007"))

# alterlative way to subset
# plotData <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]

# You cab check the date before moving on 
# str(plotData)

# Create plot variables as numeric data sets

subMetering1 <- as.numeric(plotData$Sub_metering_1)
subMetering2 <- as.numeric(plotData$Sub_metering_2)
subMetering3 <- as.numeric(plotData$Sub_metering_3)

# Create another data set which will be generated by 
# combining date and time values

plotDataDayTime <- strptime(paste(plotData$Date, plotData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 

# Generate an empty plot on screen device 

plot(datetime, subMetering1, type="n", ylab="Energy Submetering", xlab="")

# Add new data once at a time with requested color feature
# Default color is black

lines(datetime, subMetering1, type="l")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")

# Create a png file with given specs (480x480)

dev.copy(png, file = "plot3.png", width=480, height=480)

# Close the file device to finish with the file

dev.off()
